language: java
jdk:
- oraclejdk8
install: sh -c 'cd illuminator && mvn install -DskipTests=true'
script: sh -c 'cd illuminator && mvn test'
notifications:
  slack:
    secure: XCWokUB2Tbc7riRuFwneAc9OjXfX1XzweVFewHbWVA8Od6FYiywnMPi7ruggKiYQgGimiuiVpHnHyfncl20ZnQaGMOxTpy/knsCnZ0J4Q90gylBv+CwtKp7dW9HVoFdKVvtmKkWaiwxCDTSXMDDkLxNRucXN+puge4SG3qI8OQc=
